"""Generate a single self-contained SQL file from data/itsm/*.json.

Output: database/restore/restore_supabase.sql

Run order:
  1. python database/restore/gen_restore_sql.py  → writes database/restore/restore_supabase.sql
  2. Open Supabase Dashboard → SQL Editor
  3. Paste the contents of restore_supabase.sql
  4. Click Run

The generated SQL:
  - DROPs every table first (clean slate — wipes any half-restored rows)
  - Re-CREATEs each table with inferred columns
  - INSERTs every row from the JSON

Uses Supabase SQL Editor (NOT the session pooler) which has clean transaction
semantics — what you paste actually commits.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "itsm"   # database/restore/ -> repo root
OUT = Path(__file__).resolve().parent / "restore_supabase.sql"

TABLE_MAP: dict[str, str] = {
    "asset.json":               "assets",
    "catalog_item.json":        "catalog_items",
    "change.json":              "changes",
    "cmdb_ci.json":             "cmdb_cis",
    "incident.json":            "incidents",
    "kb_knowledge.json":        "kb_knowledge",
    "problem.json":             "problems",
    "request.json":             "requests",
    "sys_user.json":            "sys_users",
}

PK_FALLBACKS: dict[str, list[str]] = {
    "assets":               ["asset_id"],
    "catalog_items":        ["catalog_id", "item_id", "id"],
    "changes":              ["change_id"],
    "cmdb_cis":             ["ci_id"],
    "incidents":            ["incident_id"],
    "kb_knowledge":         ["article_id", "kb_id"],
    "problems":             ["problem_id"],
    "requests":             ["request_id"],
    "sys_users":            ["user_id", "sys_id", "id"],
}

ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}")


def _pg_type(value: Any) -> str:
    if value is None:                  return "TEXT"
    if isinstance(value, bool):        return "BOOLEAN"
    if isinstance(value, int):         return "BIGINT"
    if isinstance(value, float):       return "DOUBLE PRECISION"
    if isinstance(value, (list, dict)):return "JSONB"
    if isinstance(value, str) and ISO_RE.match(value): return "TIMESTAMPTZ"
    return "TEXT"


def _infer_cols(rows: list[dict[str, Any]]) -> dict[str, str]:
    cols: dict[str, str] = {}
    for r in rows:
        for k, v in r.items():
            inferred = _pg_type(v)
            if k not in cols or (cols[k] == "TEXT" and inferred != "TEXT"):
                cols[k] = inferred
    return cols


def _pick_pk(table: str, sample: dict) -> str | None:
    for c in PK_FALLBACKS.get(table, []):
        if c in sample:
            return c
    return None


def _sql_literal(value: Any, pg_type: str) -> str:
    """Convert a Python value to a SQL literal."""
    if value is None:
        return "NULL"
    if pg_type == "BOOLEAN":
        return "TRUE" if value else "FALSE"
    if pg_type in ("BIGINT", "DOUBLE PRECISION"):
        return str(value)
    if pg_type == "JSONB":
        return "'" + json.dumps(value).replace("'", "''") + "'::jsonb"
    if pg_type == "TIMESTAMPTZ":
        return "'" + str(value).replace("'", "''") + "'::timestamptz"
    # TEXT
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    out_lines: list[str] = [
        "-- ============================================================",
        "-- OneOps Supabase data restore",
        "-- Generated by database/restore/gen_restore_sql.py from data/itsm/*.json",
        "-- Paste into Supabase Dashboard → SQL Editor → Run",
        "-- ============================================================",
        "",
        "BEGIN;",
        "",
    ]

    total_rows = 0
    for filename, table in TABLE_MAP.items():
        path = DATA_DIR / filename
        if not path.exists():
            out_lines.append(f"-- SKIP: {filename} not found")
            continue
        rows: list[dict] = json.loads(path.read_text())
        if not rows:
            continue
        cols = _infer_cols(rows)
        pk = _pick_pk(table, rows[0])

        out_lines.append(f"-- ---- {table} ({len(rows)} rows) ---------")
        out_lines.append(f'DROP TABLE IF EXISTS "{table}" CASCADE;')
        col_defs = []
        for c, t in cols.items():
            suffix = " PRIMARY KEY" if c == pk else ""
            col_defs.append(f'  "{c}" {t}{suffix}')
        out_lines.append(f'CREATE TABLE "{table}" (')
        out_lines.append(",\n".join(col_defs))
        out_lines.append(");")
        out_lines.append("")

        col_list = ", ".join(f'"{c}"' for c in cols)
        for r in rows:
            vals = ", ".join(_sql_literal(r.get(c), cols[c]) for c in cols)
            out_lines.append(f'INSERT INTO "{table}" ({col_list}) VALUES ({vals});')
        out_lines.append("")
        total_rows += len(rows)

    out_lines.append("COMMIT;")
    out_lines.append("")
    out_lines.append(f"-- TOTAL: {total_rows} rows across {len(TABLE_MAP)} tables.")
    out_lines.append("")
    out_lines.append("-- Verify in Supabase SQL Editor:")
    out_lines.append("--   SELECT 'incidents' AS t, COUNT(*) FROM incidents")
    out_lines.append("--   UNION ALL SELECT 'requests', COUNT(*) FROM requests")
    out_lines.append("--   UNION ALL SELECT 'assets', COUNT(*) FROM assets;")

    OUT.write_text("\n".join(out_lines))
    print(f"Wrote {OUT}")
    print(f"  total rows: {total_rows}")
    print(f"  file size:  {OUT.stat().st_size:,} bytes")
    print("")
    print(f"NEXT: open Supabase Dashboard → SQL Editor → paste {OUT.name} → Run")
    return 0


if __name__ == "__main__":
    main()
