"""Seed an MFA re-enrollment catalog item for T001.

The catalog originally had no MFA-related item, causing UC-8 to flap
between NO_MATCH (when cosine top-1 fell below the floor) and
RERANK_CHOSEN→Mobile-Phone (correctly flagged UNFAITHFUL by the
judge but confusing to users). This script adds the missing template.

Idempotent: if the row exists, exits without writing.

Usage:
  .venv/bin/python scripts/uc08_seed_mfa_catalog.py
"""
from __future__ import annotations

import asyncio
import json
import os

import asyncpg

TENANT = "T001"
CAT_ID = "CAT_T001_MFA_REENROLL_30"
NAME = "MFA re-enrollment"
DESC = (
    "Re-enroll multi-factor authentication on a new or replacement device. "
    "Use when the user has a new phone, lost their old device, or needs to "
    "reset their MFA token. Covers SMS, authenticator-app (TOTP), and "
    "hardware-token re-binding for any user account."
)
CATEGORY = "access"
OWNER = "GRP-IDENTITY"
TOTAL_MINUTES = 32

# All steps are MANUAL: the IdP team (GRP-IDENTITY) performs them. There is
# no MFA/IdP integration in the adapter, so marking these `automated` without
# a tool_id would silently no-op at runtime (the very defect the catalog
# completeness guardrail forbids). They are honest owner-group work.
TASKS = [
    {
        "task_id": "VERIFY_IDENTITY",
        "name": "Verify requester identity",
        "type": "manual",
        "depends_on": [],
        "owner_group": OWNER,
        "estimated_minutes": 10,
        "approval_required": False,
    },
    {
        "task_id": "REVOKE_OLD_TOKEN",
        "name": "Revoke prior MFA token from IdP",
        "type": "manual",
        "depends_on": ["VERIFY_IDENTITY"],
        "owner_group": OWNER,
        "estimated_minutes": 5,
        "approval_required": False,
    },
    {
        "task_id": "ENROLL_NEW_DEVICE",
        "name": "Send re-enrollment link and confirm new device binding",
        "type": "manual",
        "depends_on": ["REVOKE_OLD_TOKEN"],
        "owner_group": OWNER,
        "estimated_minutes": 15,
        "approval_required": False,
    },
    {
        "task_id": "NOTIFY_USER",
        "name": "Notify user re-enrollment complete",
        "type": "manual",
        "depends_on": ["ENROLL_NEW_DEVICE"],
        "owner_group": OWNER,
        "estimated_minutes": 2,
        "approval_required": False,
    },
]


async def main() -> None:
    c = await asyncpg.connect(os.environ["POSTGRES_URL"])
    try:
        existing = await c.fetchval(
            "SELECT catalog_item_id FROM itsm.catalog_item "
            "WHERE tenant_id=$1 AND catalog_item_id=$2",
            TENANT, CAT_ID,
        )
        if existing:
            print(f"already present: {existing}")
            return
        await c.execute(
            """
            INSERT INTO itsm.catalog_item
              (tenant_id, catalog_item_id, name, description, category,
               owner_group, estimated_total_minutes, tasks)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb)
            """,
            TENANT, CAT_ID, NAME, DESC, CATEGORY, OWNER,
            TOTAL_MINUTES, json.dumps(TASKS),
        )
        print(f"✅ inserted {CAT_ID}")
        print("   embedding will be generated by the catalog-item trigger.")
    finally:
        await c.close()


if __name__ == "__main__":
    asyncio.run(main())
