"""Seed a Password reset procedure KB article for T001.

The T001 KB had only KB0005008 (MFA reset propagation guide) for
password/reset queries, causing UC-3 to honestly return "no good
match" for "where do I find the password reset procedure". This
script adds the missing article so the natural-language query lands
on a real article above the 0.50 relevance gate.

Idempotent: exits cleanly if the kb_id already exists. Embedding is
auto-generated by the kb_knowledge trigger.

Usage:
  .venv/bin/python scripts/uc03_seed_password_reset_kb.py
"""
from __future__ import annotations

import asyncio
import os

import asyncpg

TENANT = "T001"
KB_ID = "KB0005021"
TITLE = "Password reset procedure"
SUMMARY = (
    "Standard procedure for resetting a user's password — self-service "
    "portal flow, helpdesk-assisted reset, and post-reset checks."
)
CONTENT = """\
# Password reset procedure

## When to use this
- User has forgotten their password.
- Password compromise suspected (phishing, leaked credentials).
- Periodic password rotation required by policy.

## Symptom
- User cannot log in with current credentials.
- "Incorrect password" error from IdP.
- Account lockout after multiple failed attempts.

## Resolution

### Self-service path (preferred)
1. User navigates to the corporate identity portal at https://idp.corp/reset.
2. User enters their work email address.
3. System sends a one-time reset link valid for 15 minutes to the
   registered recovery email or phone.
4. User clicks the link, sets a new password meeting the complexity
   policy (≥ 12 chars, 1 upper, 1 digit, 1 symbol, no last-5 reuse).
5. New password propagates to all federated services within 5 minutes.

### Helpdesk-assisted path
1. Helpdesk agent verifies caller identity (employee id + manager
   approval + one government id).
2. Agent triggers a manual reset from the IdP admin console.
3. Agent provides a temporary password over an authenticated channel
   (in-person hand-off, internal phone).
4. User must change the temporary password at first login.
5. Agent files an audit entry in the IAM ticket queue.

### Post-reset checks
- Confirm user can log in to: corporate IdP, VPN, email, ticketing.
- If MFA is enabled, see KB0005008 for MFA re-enrollment when the
  device has changed.
- Stale session tokens should be cleared automatically; force a
  device-side logout if not.

## Source
- Internal IT IAM policy v3.2 §5.1
- IdP runtime: Azure AD / Okta (see CMDB CI for the active provider)
"""

CATEGORY = "access"
TAGS = ["password", "reset", "iam", "authentication", "self-service"]
AUDIENCE = "end_user"
CREATED_BY = "USR00001"


async def main() -> None:
    c = await asyncpg.connect(os.environ["POSTGRES_URL"])
    try:
        existing = await c.fetchval(
            "SELECT kb_id FROM itsm.kb_knowledge "
            "WHERE tenant_id=$1 AND kb_id=$2",
            TENANT, KB_ID,
        )
        if existing:
            print(f"already present: {existing}")
            return
        await c.execute(
            """
            INSERT INTO itsm.kb_knowledge
              (tenant_id, kb_id, title, summary, content, category,
               tags, state, audience, created_by)
            VALUES ($1, $2, $3, $4, $5, $6, $7, 'published', $8, $9)
            """,
            TENANT, KB_ID, TITLE, SUMMARY, CONTENT, CATEGORY,
            TAGS, AUDIENCE, CREATED_BY,
        )
        print(f"✅ inserted {KB_ID}")
        print("   embedding will be generated by the kb_knowledge trigger.")
    finally:
        await c.close()


if __name__ == "__main__":
    asyncio.run(main())
